### ISSUE TITLE
Send email notification when Pending Muhtar is confirmed or rejected

### ISSUE THREAD

**Issue by ldanielswakman** [Muhit-co/issues-archive#104]
An email should go out to the Muhtar email address whenever an admin changes a pending muhtar status from 'pending' (level 4) to confirmed (level 5) or rejected (level 3). These are separate email templates, and will be delivered as laravel views by @ldanielswakman.

**Comment by ldanielswakman** [comment]
Added 2 email templates for approve & reject emails.
https://github.com/Muhit-co/api/commit/14e2d0b141aae2605006ae048ddc6f3270b13363

**Comment by ldanielswakman** [comment]
Related to this issue: send an email to all super admin users when a muhtar requests a sign up

**Comment by ghost** [comment]
@ldanielswakman how can i register as muhtar or request a muhtar signup?

**Comment by ldanielswakman** [comment]
muhit.app/register-muhtar for the signup form, then you can change the level from 4 (pending) to 5 (accepted), either by logging in as an admin or from the db

**Comment by ldanielswakman** [comment]
This issue was moved to Muhit-co/api#90
