### ISSUE TITLE
Show muhtar info for user ('Muhtarım' menu option)

### ISSUE THREAD

**Issue by ldanielswakman** [Muhit-co/issues-archive#118]
_Problem_
When normal user is logged in, clicking on the 'Muhtarım' menu item redirects them to a new page, but the menu disappears and no muhtar info is shown. 

![image](https://cloud.githubusercontent.com/assets/4538367/15550680/4bd1b2f6-22bb-11e6-8463-493951860853.png)

![image](https://cloud.githubusercontent.com/assets/4538367/15550687/558e4980-22bb-11e6-852d-cae5db385fea.png)

_Expected behaviour_
When clicking the 'Muhtarım' menu item, the user should see the Muhtar profile info (same as the user show page for a muhtar). If there is no Muhtar signed up for that Mahalle, the empty state (see current) should be displayed. The menu should be visible.

**Comment by ghost** [comment]
@ldanielswakman check it please

didn't app map view -- because of google maps api implementation and coordinates etc so commented out.

**Comment by ldanielswakman** [comment]
What do you mean with map view? For showing info we can use the muhtar profile info as listed on /members/my-profile (when logged in as muhtar).
`views/pages/profile.blade.php`

![image](https://cloud.githubusercontent.com/assets/4538367/15781866/b1f5f42e-29b0-11e6-8193-946720145a38.png)

I saw some visual issues; I'll handle those as long as the data is outputted to the page okay? And main thing is that the menu is not showing yet.

![image](https://cloud.githubusercontent.com/assets/4538367/15781848/95be9a68-29b0-11e6-9f21-f014f92c6924.png)

**Comment by ghost** [comment]
hey @ldanielswakman just committed it.

**Comment by ldanielswakman** [comment]
@ersoypembe I did a brief test and it looks good. If you open up a pull request, we can merge it.
