### ISSUE TITLE
iOS sentry integration

### ISSUE THREAD

**Issue by gcg** [Muhit-co/issues-archive#14]
Emre seni githuba almamışlar :) 

sen github a girince sentry entegrasyonunu yapabilrsen süper olur :) 

DSN: https://a99355627f1b4f879988b7b333f6c3ff:263a42d3689445aa93190906060a14a5@app.getsentry.com/46406

Dokumantasyon: 
https://app.getsentry.com/docs/platforms/?pid=46406

**Comment by ldanielswakman** [comment]
This issue was moved to Muhit-co/ios#9
