### ISSUE TITLE
Delete issue only when issue is in "oluşturuldu" status and has less than 10 supporters

### ISSUE THREAD

**Issue by seratolgay** [Muhit-co/issues-archive#24]

**Comment by ldanielswakman** [comment]
implemented in views to only show delete button when issue has less than 10 supporters; @gcg should have a server-side check as well?

**Comment by gcg** [comment]
what is oluşturuldu status means @ldanielswakman ? 

is it new?

**Comment by ldanielswakman** [comment]
@gcg yes it is new
