### ISSUE TITLE
show issue location on map in show page

### ISSUE THREAD

**Issue by ldanielswakman** [Muhit-co/issues-archive#40]

**Comment by gcg** [comment]
@ldanielswakman I saw a mapInitialize function on show page but I see no marker on the map that generated. do you know why?

**Comment by ldanielswakman** [comment]
@gcg `mapInitialize()` sits in `maps.js`; currently it doesn't take parameters so the dummy `mapdata.json` gets loaded as a data source. I think we have to make that dynamic

**Comment by gcg** [comment]
is that func dedicated to the show page or you are using the same thing in the list page as well ?

**Comment by ldanielswakman** [comment]
both show and list. If possible of course simpler to just use the same function, but we can also split it if necessary

– by the way we also need  to make the zoom level dynamic based on how many / which markers are shown
