### ISSUE TITLE
Muhtar signup 

### ISSUE THREAD

**Issue by gcg** [Muhit-co/issues-archive#42]
hey man, 

it would be awesome for me inorder to finish muhtar related issues (show muhtar comments on issue detail page, muhtar announcements and muhtar profile pages) to have a muhtar :) 

How is the process of becoming a muhtar goes? 

Which page do I signup as a muhtar and who authorizes it ?

**Comment by ldanielswakman** [comment]
You can most simply 'make' a user a muhtar by giving it a `level` more than 5 and less than 10. The register muhtar page should create a user like normal, but don't allow access yet until it is verified by us (super admins). We would need a specialised error message for that on the login screen; and a way for us (super admins) to allow/disallow muhtar sign up requests.

**Comment by ldanielswakman** [comment]
@gcg did you assign it to me for a reason? I designed the sign-up form; we now need the backend logic for a muhtar or belediye user to be created, but have a 'on hold' status and a custom flash message content when an unconfirmed muhtar/belediye tries to sign in

– btw it would be good to distinguish between a muhtar and a belediye. Could you take this into account?  I need to add some logic for it in the form, will make an issue for that

**Comment by gcg** [comment]
arighty.
