### ISSUE TITLE
issue statuses 

### ISSUE THREAD

**Issue by gcg** [Muhit-co/issues-archive#43]
@ldanielswakman @seratolgay 

is there a list for possible issue statuses ? 

new, (or draft if we want to pre-approve stuff) 
supported
resolved
...

**Comment by ldanielswakman** [comment]
Currently we have:
- new
- supported (>= 10 supporters)
- in progress
- solved

_NB1:_ I guess in the backend side we will also have 'deleted'; if a user deletes an issue we will keep a record in the DB? Currently we don't have a 'draft' status.

_NB2:_ A user is only allowed to support an issue if its status is 'new', 'supported' or 'in progress'; and only allowed to delete issues they themselves created if status is 'new'

Any other info you need on this?

**Comment by gcg** [comment]
what is the difference between in progress and supported ?

**Comment by ldanielswakman** [comment]
with 'supported' the issue got created, and has received more than 9 supporters, but has not been 'taken into development' by the muhtar. An issue can only get to 'in progress' or 'solved' states if a muhtar or belediye changes the status:

![screen shot 2015-07-28 at 18 25 05](https://cloud.githubusercontent.com/assets/4538367/8935563/0fefbb00-3556-11e5-9369-4b050aefa107.png)

**Comment by gcg** [comment]
I see, thank you

**Comment by ldanielswakman** [comment]
@gcg Is this still an issue or can it be closed?
