### ISSUE TITLE
create test accounts on staging/production db

### ISSUE THREAD

**Issue by ldanielswakman** [Muhit-co/issues-archive#53]
@gcg could you make 3 types of test users on the staging server db for different role so we could try them out? Let's say 'test_user@muhit.co' (level 1), 'test_muhtar@muhit.co' (level 5) and 'test_belediye@muhit.co' (level 7)? All passwords `cayimiic`

And super admin users (level 10) for sera, ece, daniel and guney with their muhit email addresses ( [name]@muhit.co )

**Comment by gcg** [comment]
I created the test users and give the level 10 to your, ece's and sera's current accounts on muhit.
