### ISSUE TITLE
populate tags list

### ISSUE THREAD

**Issue by ldanielswakman** [Muhit-co/issues-archive#6]
tag list:

| name | colour |
| --- | --- |
| Kıyı | bg-tag-blue |
| Aydınlatma | bg-tag-yellow |
| Bisiklet | bg-tag-pink |
| Trafik ışığı | bg-tag-red |
| Yaya | bg-tag-orange |
| Sürdürülebilir | bg-tag-teal |
| Ağaçlandırma | bg-tag-lightgreen |
| Park | bg-tag-green |
| Enerji | bg-tag-purple |
| Geri dönüşüm | bg-tag-brown |
| Diğer | bg-tag-grey |

**Comment by gcg** [comment]
give me hex!

**Comment by ldanielswakman** [comment]
| name | colour | hex |
| --- | --- | --- |
| Kıyı | bg-tag-blue | #629acc |
| Aydınlatma | bg-tag-yellow | #eae657 |
| Bisiklet | bg-tag-pink | #e8a0c1 |
| Trafik ışığı | bg-tag-red | #ea6d4b |
| Yaya | bg-tag-orange | #f2b42c |
| Sürdürülebilir | bg-tag-teal | #7dd3ac |
| Ağaçlandırma | bg-tag-lightgreen | #a7cc81 |
| Park | bg-tag-green | #7ea56d |
| Enerji | bg-tag-purple | #c673c0 |
| Geri dönüşüm | bg-tag-brown | #c4a26c |
| Diğer | bg-tag-grey | #ccccdd |
