### ISSUE TITLE
Implement dashboard interface for admin pages

### ISSUE THREAD

**Issue by ldanielswakman** [Muhit-co/issues-archive#9]
We'll be using a ready-made panel such as
http://startangular.com/product/rdash-angularjs/

Perhaps discussion needed with @ldanielswakman about how to implement

**Comment by ldanielswakman** [comment]
@gcg do you have a suggestion for a simple dashboard admin interface we can 'slap on' without doing much work on this? It should allow us to simply list all issues, announcements, comments, users, do create, edit and delete actions on all of them.

**Comment by gcg** [comment]
we can buy an admin theme from themeforest and use it with php backend. 

There will be work involved but I think it is the safest course

**Comment by ldanielswakman** [comment]
Sounds good; which one would you recommend?
